spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

blog-api:
  datasource:
    mysql:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/blogs?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
        username: test
        password: test
        pool-name: HikariPool-Blog-APP-Master
        maximum-pool-size: 2
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/blogs?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
        username: test
        password: test
        pool-name: HikariPool-Blog-APP-Slave
        maximum-pool-size: 2
#    main:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3307/blog
#      username: test
#      password: test

---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live